<?php

namespace AppBundle\Repository;

/**
 * TodosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodosRepository extends \Doctrine\ORM\EntityRepository
{
}
